### ISSUE TITLE
Support for GH package registry

### ISSUE THREAD

**Issue by jfbrennan** [tehpsalmist/npm-publish-status-action#37]
I was expecting to be able to run this for a package I publish to a private GH package registry by setting `registry-url`. My workflow file:
```
name: Publish package

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Check publish status
        id: check
        uses: tehpsalmist/npm-publish-status-action@v1

      - name: Publish package
        if: steps.check.outputs.exists == '0'
        run: |
          npm install
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: No publish
        if: steps.check.outputs.exists == '1'
        run: 'echo "No version change. Package will not be published."'
```

Seems like this should just work, but apparently not. This action hardcodes npmjs https://github.com/tehpsalmist/npm-publish-status-action/blob/master/src/main.ts#L39

Can you change this to use `registry-url` if set? (I'd send a PR but I have no experience with writing GH actions)
